src/main/java/ipass/model/Dienst.java
package ipass.model;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Dienst {
	private int ID;
	private String naam;
	private double opbrengst;
	private Date datum;
	
	public Dienst(int ID, String naam, double opbrengst, Date datum){
		this.ID = ID;
		this.naam = naam;
		this.opbrengst = opbrengst;
		this.datum = datum;
	}
	public int getID(){
		return ID;
	}

	public String getNaam() {
		return naam;
	}

	public double getOpbrengst() {
		return opbrengst;
	}

	public Date getDatum() {
		return datum;
	}
	
	public String getSimpelDatum() {
		DateFormat df = new SimpleDateFormat("dd-mm-yyyy"); 
		String datum = df.format(this.datum);
		return datum;
	}
	
}

src/main/java/ipass/controller/KlantInfoServlet.java
package ipass.controller;

import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import ipass.domain.service.KlantenService;
import ipass.domain.service.ServiceProvider;
import ipass.model.Dienst;
import ipass.model.Klant;

public class KlantInfoServlet extends HttpServlet{
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		int ID = Integer.parseInt(req.getParameter("klant_id"));
		int opbrengst_totaal = 0;
		
		RequestDispatcher rd = null;
	
		KlantenService service = ServiceProvider.getKlantenService();
		Klant k = service.getKlant(ID);
		ArrayList<Dienst> afgenomenDiensten = k.getAfgenomenDiensten();
		
		for(Dienst d : afgenomenDiensten){
			opbrengst_totaal += d.getOpbrengst();
		}
		
		req.setAttribute("klantInfo", k);
		req.setAttribute("bezoeken", afgenomenDiensten.size());
		req.setAttribute("totaal", opbrengst_totaal);
		try{
		    req.setAttribute("gemopbrengst", opbrengst_totaal/afgenomenDiensten.size());
		}catch(Exception e){
			req.setAttribute("gemopbrengst", 0);
		}
		req.setAttribute("afgenomenDiensten", afgenomenDiensten);
		try{
			req.setAttribute("laatstebezoek", afgenomenDiensten.get(afgenomenDiensten.size()-1).getDatum());
		}catch(Exception e){
			req.setAttribute("laatstebezoek", new Date());
		}
		rd = req.getRequestDispatcher("/admin/klant_info.jsp");

		rd.forward(req, resp);
		
	}
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		int ID = Integer.parseInt(req.getParameter("klant_id"));
		String voornaam = req.getParameter("voornaam");
		String achternaam = req.getParameter("achternaam");
		String gbdatum = req.getParameter("gbdatum");
		String email = req.getParameter("email");
		String woonplaats = req.getParameter("woonplaats");
		int personen = Integer.parseInt(req.getParameter("personen"));
		String telefoon = req.getParameter("telefoon");
		int active = Integer.parseInt(req.getParameter("active"));
		
		RequestDispatcher rd = null;

		
		if(voornaam.equals(null) || voornaam == null){
			req.setAttribute("msgs", "Voornaam is niet correct of leeg!");
			rd = req.getRequestDispatcher("/admin/new_klant.jsp");
		}else if(achternaam.equals(null) || achternaam == null){
			req.setAttribute("msgs", "Achternaam is niet correct of leeg!");
			rd = req.getRequestDispatcher("/admin/new_klant.jsp");
		}else if(gbdatum.equals(null) || gbdatum == null){
			req.setAttribute("msgs", "Geboortedatum is niet correct of leeg!");
			rd = req.getRequestDispatcher("/admin/new_klant.jsp");
		}else if(woonplaats.equals(null) || woonplaats == null){
			req.setAttribute("msgs", "Woonplaats is niet correct of leeg!");
			rd = req.getRequestDispatcher("/admin/new_klant.jsp");
		}else if(personen == 0){
			req.setAttribute("msgs", "Het aantal personen is niet correct of leeg!");
			rd = req.getRequestDispatcher("/admin/new_klant.jsp");
		}else{
			KlantenService service = ServiceProvider.getKlantenService();
			if(service.updateKlant(ID, voornaam, achternaam, gbdatum, woonplaats, personen, email, telefoon, active) == 1){
				req.setAttribute("succes", "De klantgegevens zijn aangepast!");
				rd = req.getRequestDispatcher("/admin/klanten.jsp");
			}else if(service.addKlant(voornaam, achternaam, gbdatum, woonplaats, personen, email, telefoon) == 2){
				req.setAttribute("msgs", "Er bestaat al een klant met dit email adres!");
				rd = req.getRequestDispatcher("/admin/klanten.jsp");
			}else{
				req.setAttribute("msgs", "Er is iets fout gegaan, probeer het later opnieuw!");
				rd = req.getRequestDispatcher("/admin/klanten.jsp");
			}
		}

		rd.forward(req, resp);
		
	}
}

src/main/webapp/admin/alle_klanten.jsp
<jsp:include page="../includes/header.jsp" />
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="ipass.domain.service.ServiceProvider" %>
<% request.setAttribute("service", ServiceProvider.getKlantenService()); %>
<div class="wrap-content">
	<div class="container">
		<div class="paddinglg"></div>
		<div class="whitebg">
		<div class="paddingsm"></div>
			<c:if test="${msgs != null}">
		<div class="alert alert-danger" role="alert">${msgs} </div>	  
		<div class="paddingsm"></div>
	</c:if>
	<c:if test="${succes != null}">
		<div class="alert alert-success" role="alert">${succes} </div>	  
		<div class="paddingsm"></div>
	</c:if>
		<div class="row">
			<div class="col-sm-6"><h1 class="title">Klantoverzicht</h1></div>
			<div class="col-sm-6"><input type="text" class="form-control" id="search" placeholder="Typ om te zoeken..." /></div>
		</div>
		
		<div class="paddingmd"></div>
		<table class="table table-striped table-bordered tablesorter" id="klant_table">
			<thead>
				<tr>
					<th>Voornaam</th>
					<th>Achternaam</th>
					<th>Geboortedatum</th>
					<th>Email</th>
					<th>Woonplaats</th>
					<th>Formaat huishouden</th>
					<th>Telefoon</th>
					<th>Actief</th>
					<th>Details</th>
					<th>Verwijderen</th>
				</tr>
			</thead>
			<tbody>
			<c:forEach var="klant" items="${service.getKlanten()}">
				<tr>
					<td>${klant.voornaam}</td>
					<td>${klant.achternaam}</td>
					<td>${klant.gbdatum}</td>
					<td>${klant.email}</td>
					<td>${klant.woonplaats}</td>
					<td>${klant.huishouden}</td>
					<td>${klant.telefoon}</td>
					<c:choose>
					<c:when test="${klant.active == 1}">
						<td>Actief</td>
					</c:when>
					<c:otherwise>
						<td>Inactief</td>
					</c:otherwise>
					</c:choose>
					<td><form action="/admin/klant_info" method="get"><button class="btn btn-primary" name="klant_id" id="delete_button" value="${klant.ID}" type="submit">Details</button></form></td>
					<td><form action="/admin/delete" method="post" id="delete"><button class="btn btn-primary" name="delete" id="delete_button" type="submit" value="${klant.ID}">Verwijderen</button></form></td> 
				</tr>
			</c:forEach>
			</tbody>
		</table>
		<div class="paddingsm"></div>
		</div>
	</div>
	<div class="add_klant">
		<form action="/admin/refresh" method="post"><button class="refresh" name="refresh" id="refresh"  type="submit"><i class="fa fa-refresh"></i></button></form>
	</div>
</div>


<jsp:include page="../includes/footer.jsp" />


src/main/webapp/admin/klant_info.jsp
<jsp:include page="../includes/header.jsp" />
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<div class="wrap-content">
	<div class="container">
		<div class="paddinglg"></div>
			<div class="row">
				<div class="col-xs-12">
					<ul class="nav nav-tabs" role="tablist">
					    <li role="presentation" class="active"><a href="#data" aria-controls="data" role="tab" data-toggle="tab">Gegevens aanpassen</a></li>
					    <li role="presentation"><a href="#worth" aria-controls="worth" role="tab" data-toggle="tab">Klantwaarde</a></li>
					    <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">Klantgeschiedenis</a></li>
					     <li role="presentation"><a href="#dienst" aria-controls="dienst" role="tab" data-toggle="tab">Nieuwe dienst afgenomen</a></li>
				  	</ul>
				</div>
			</div>
			<div class="tab-content">
			    <div role="tabpanel" class="tab-pane active" id="data">
				    <div class="whitebg">
				    	<div class="paddingsm"></div>
				    		<c:if test="${msgs != null}">
								<div class="alert alert-danger" role="alert">${msgs} </div>	  
								<div class="paddingsm"></div>
							</c:if>
							<c:if test="${succes != null}">
								<div class="alert alert-success" role="alert">${succes} </div>	  
								<div class="paddingsm"></div>
							</c:if>
					   <form action="/admin/klant_info" method="post">
							<div class="row">
								<div class="col-sm-6">
								 <input type="text" name="klant_id" class="display_none" id="klant_id" value="${klantInfo.ID}" >
								  <div class="form-group">
								    <label for="voornaam">Voornaam</label>
								    <input type="text" name="voornaam" class="form-control" id="voornaam" value="${klantInfo.voornaam}" readonly>
								  </div>
								  <div class="form-group">
								    <label for="achternaam">Achternaam</label>
								    <input type="text" name="achternaam" class="form-control" id="achternaam" value="${klantInfo.achternaam}" readonly>
								  </div>
								   <div class="form-group">
								    <label for="gbdatum">Geboorte datum</label>
								    <input type="date" name="gbdatum" class="form-control" id="gbdatum" value="${klantInfo.gbdatum}" readonly>
								  </div>
					
								  <div class="paddingmd"></div>
								</div>
								
								
								<div class="col-sm-6">
								  <div class="form-group">
								    <label for="email">Email</label>
								    <input type="email" name="email" class="form-control" id="email" value="${klantInfo.email}" placeholder="Email">
								  </div>
								  <div class="form-group">
								    <label for="woonplaats">Woonplaats</label>
								    <input type="text" name="woonplaats" class="form-control" id="woonplaats" value="${klantInfo.woonplaats}" required>
								  </div>
								   <div class="form-group">
								    <label for="telefoon">Telefoon</label>
								    <input type="text" name="telefoon" class="form-control" id="telefoon" value="${klantInfo.telefoon}" required>
								  </div>
								  <div class="form-group">
								    <label for="personen">Personen in huishouden</label>
								    <input type="number" name="personen" class="form-control bfh-number" id="personen" value="${klantInfo.huishouden}" min="1" max="20" required>
								  </div>
								  <div class="form-group">
								    <label for="gbdatum">Actief:</label>
								    <select name="active" class="form-control" id="active">
								    <option value="1" <c:if test="${klantInfo.active == 1}">selected</c:if>>Actief</option>
								    <option value="0" <c:if test="${klantInfo.active == 0}">selected</c:if>>Inactief</option>
								    </select>
								  </div>
								  <div class="form-group">
								    <input type="submit" class="btn btn-primary text-right" value="Aanpassen">
								  </div>
								  <div class="paddingmd"></div>
								</div>

							</div>
						</form>
				    </div>
			    </div>
			    <div role="tabpanel" class="tab-pane" id="worth">
			    <div class="whitebg worth">
			    	<div class="paddingsm"></div>
			    	<div class="row">
						<div class="col-sm-3">
							<p>Totale opbrengst:</p>
							<p>${totaal}</p>
						</div>
						<div class="col-sm-3">
							<p>Aantal bezoeken:</p>
							<p>${bezoeken}</p>
						</div>
						<div class="col-sm-3">
							<p>Gem. opbrengst per bezoek:</p>
							<p>${gemopbrengst}</p>
						</div>
						<div class="col-sm-3">
							<p>Laatste bezoek:</p>
							<p><fmt:formatDate pattern="dd-MM-yyyy"  value="${laatstebezoek}" /></p>
						</div>
					</div>
					<div class="paddingsm"></div>
				</div>
			    </div>
			    <div role="tabpanel" class="tab-pane" id="history">
			    <div class="whitebg">
			    	<div class="row">
			    	<div class="col-sm-12">
			    	<h3>Orderhistory</h3>
			    	<table class="table table-hover">
			    		<thead>
					      <tr>
					        <th>Naam</th>
					        <th>Opbrengst</th>
					        <th>Datum</th>
					      </tr>
					    </thead>
						<tbody>
							<c:forEach var="dienst" items="${afgenomenDiensten}">
							<tr>
							<td>${dienst.naam}</td>
							<td>${dienst.opbrengst}</td>
							<td><fmt:formatDate pattern="dd-MM-yyyy"  value="${dienst.datum}" /></td>
							</tr>
							</c:forEach>
						</tbody>
						</table>
						  <div class="paddingmd"></div>
						</div>
					</div>
			    </div>
			    </div>
			   <div role="tabpanel" class="tab-pane" id="dienst">
			    <div class="whitebg">
			    	<div class="paddingsm"></div>
			    		<c:if test="${msgs_dienst != null}">
							<div class="alert alert-danger" role="alert">${msgs_dienst} </div>	  
							<div class="paddingsm"></div>
						</c:if>
						<c:if test="${succes_dienst != null}">
							<div class="alert alert-success" role="alert">${succes_dienst} </div>	  
							<div class="paddingsm"></div>
						</c:if>
				   <form action="/admin/nieuwe_dienst" method="post">
						<div class="row">
							<div class="col-sm-6">
							 <input type="text" name="klant_id" class="display_none" id="klant_id" value="${klantInfo.ID}" >
							  <div class="form-group">
							    <label for="voornaam">Naam</label>
							    <input type="text" name="naam" class="form-control" id="naam" required>
							  </div>
							  <div class="form-group">
							    <label for="achternaam">Datum</label>
							    <input type="date" name="datum" class="form-control datepicker" id="datum" required>
							  </div>
				
							  <div class="paddingmd"></div>
							</div>
							
							<div class="col-sm-6">
							  <div class="form-group">
							    <label for="achternaam">Opbrenst</label>
							    <input type="number" step="0.01" name="opbrengst" class="form-control" id="opbrengst" required>
							  </div>
							  <div class="form-group">
							  <br>
							    <input type="submit" class="btn btn-primary text-right" value="Toevoegen">
							  </div>
							  <div class="paddingmd"></div>
							</div>

						</div>
					</form>
			    </div>
		    </div>
		  	</div>

	</div>
	<div class="add_klant">
		<a href="/admin/new_klant.jsp"><i class="fa fa-plus"></i></a>
	</div>
</div>


<jsp:include page="../includes/footer.jsp" />


src/main/webapp/admin/klanten.jsp
<jsp:include page="../includes/header.jsp" />
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="ipass.domain.service.ServiceProvider" %>
<% request.setAttribute("service", ServiceProvider.getKlantenService()); %>
<div class="wrap-content">
	<div class="container">
		<div class="paddinglg"></div>
		<div class="whitebg">
		<div class="paddingsm"></div>
			<c:if test="${msgs != null}">
		<div class="alert alert-danger" role="alert">${msgs} </div>	  
		<div class="paddingsm"></div>
	</c:if>
	<c:if test="${succes != null}">
		<div class="alert alert-success" role="alert">${succes} </div>	  
		<div class="paddingsm"></div>
	</c:if>
		<div class="row">
			<div class="col-sm-6"><h1 class="title">Klantoverzicht</h1></div>
			<div class="col-sm-6"><input type="text" class="form-control" id="search" placeholder="Typ om te zoeken..." /></div>
		</div>
		
		<div class="paddingmd"></div>
		<table class="table table-striped table-bordered tablesorter" id="klant_table">
			<thead>
				<tr>
					<th>Voornaam</th>
					<th>Achternaam</th>
					<th>Geboortedatum</th>
					<th>Email</th>
					<th>Woonplaats</th>
					<th>Formaat huishouden</th>
					<th>Telefoon</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
			<c:forEach var="klant" items="${service.getActieveKlanten()}">
				<tr>
					<td>${klant.voornaam}</td>
					<td>${klant.achternaam}</td>
					<td>${klant.gbdatum}</td>
					<td>${klant.email}</td>
					<td>${klant.woonplaats}</td>
					<td>${klant.huishouden}</td>
					<td>${klant.telefoon}</td>
					<td><form action="/admin/klant_info" method="get"><button class="btn btn-primary" name="klant_id" id="delete_button" value="${klant.ID}" type="submit">Details</button></form></td>
					<!--<td><form action="/admin/delete" method="post" id="delete"><button class="btn btn-primary" name="delete" id="delete_button" type="submit" value="${klant.ID}">Verwijderen</button></form></td> -->
				</tr>
			</c:forEach>
			</tbody>
		</table>
		<div class="paddingsm"></div>
		</div>
	</div>
	<div class="add_klant">
		<a href="/admin/new_klant.jsp"><i class="fa fa-plus"></i></a>
	</div>
</div>


<jsp:include page="../includes/footer.jsp" />


src/main/webapp/admin/new_klant.jsp
<jsp:include page="../includes/header.jsp" />
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="ipass.domain.service.ServiceProvider" %>
<% request.setAttribute("service", ServiceProvider.getKlantenService()); %>
<div class="wrap-content">
	<div class="container">
	<div class="paddinglg"></div>
	<c:if test="${msgs != null}">
		<div class="alert alert-danger" role="alert">${msgs} </div>	  
		<div class="paddinglg"></div>
	</c:if>
	<c:if test="${succes != null}">
		<div class="alert alert-success" role="alert">${succes} </div>	  
		<div class="paddinglg"></div>
	</c:if>
		<div class="whitebg">
			<div class="paddingmd"></div>
			<h1>Klant aanmaken</h1>
			<div class="paddingsm"></div>
			<form action="CreateUserServlet.do" method="post">
				<div class="row">
					<div class="col-sm-6">
					  <div class="form-group">
					    <label for="voornaam">Voornaam</label>
					    <input type="text" name="voornaam" class="form-control" id="voornaam" placeholder="Voornaam" required>
					  </div>
					  <div class="form-group">
					    <label for="achternaam">Achternaam</label>
					    <input type="text" name="achternaam" class="form-control" id="achternaam" placeholder="Achternaam" required>
					  </div>
					   <div class="form-group">
					    <label for="gbdatum">Geboorte datum</label>
					    <input type="date" name="gbdatum" class="form-control" id="gbdatum" placeholder="Geboorte datum" required>
					  </div>
					  <div class="paddingmd"></div>
					</div>
					
					
					<div class="col-sm-6">
					  <div class="form-group">
					    <label for="email">Email</label>
					    <input type="email" name="email" class="form-control" id="email" placeholder="Email" required>
					  </div>
					  <div class="form-group">
					    <label for="woonplaats">Woonplaats</label>
					    <input type="text" name="woonplaats" class="form-control" id="woonplaats" placeholder="Woonplaats" required>
					  </div>
					  <div class="form-group">
					    <label for="personen">Personen in huishouden</label>
					    <input type="number" name="personen" class="form-control bfh-number" id="personen" value="1" min="1" max="20" required>
					  </div>
					  <div class="form-group">
					    <label for="personen">Telefoonnummer</label>
					    <input type="tel" name="telefoon" class="form-control" id="telefoon" required>
					  </div>
					  <div class="form-group">
					    <input type="submit" class="btn btn-primary text-right" value="aanmaken">
					  </div>
					  <div class="paddingmd"></div>
					</div>

				</div>
			</form>
		</div>
	</div>
</div>


<jsp:include page="../includes/footer.jsp" />


src/main/webapp/admin/panel.jsp
<jsp:include page="../includes/header.jsp" />
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ page import="ipass.domain.service.ServiceProvider" %>
<% request.setAttribute("service", ServiceProvider.getDienstenService()); %>
<% request.setAttribute("klanten", ServiceProvider.getKlantenService().getBesteKlanten()); %>
 <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart', 'bar']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        
        
        data.addColumn('string', 'Datum');
        data.addColumn('number', 'Omzet');
        <c:forEach var="klant" items="${service.getThisWeekProfit()}">
        data.addRow(['${klant.simpelDatum}',${klant.opbrengst}]);
    	</c:forEach>
        // Set chart options
        var options = {'title':'Omzet per dag',
                       'width':500,
                       'height':300};
        
        var data2 = new google.visualization.DataTable();
        
        
        data2.addColumn('string', 'Naam');
        data2.addColumn('number', 'Opbrengst');
        <c:forEach begin="0" end="${fn:length(klanten)-1}" step="2" var="loop">
        data2.addRow(['${klanten.get(loop)}',${klanten.get(loop+1)}]);
    	</c:forEach>
        // Set chart options
        var options2 = {'title':'Meest waardevolle klanten',
                       'width':500,
                       'height':300,
                       is3D: true};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.ColumnChart(document.getElementById('bar_chart_div'));
        chart.draw(data, options);
        var chart2 = new google.visualization.ColumnChart(document.getElementById('bar_chart_div2'));
        chart2.draw(data2, options2);
        
        
      }
     
</script>

<div class="wrap-content">
	<div class="container">
		<div class="paddinglg"></div>
		<div class="row">
			<div class="col-sm-6">
				<div id="bar_chart_div"></div>
			</div>
			<div class="col-sm-6">
				<div id="bar_chart_div2"></div>
			</div>
		</div>
		
	</div>
</div>

<jsp:include page="../includes/footer.jsp" />
